name: flutter_pokedex
description: A Flutter Pokedex

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  bordered_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.2
  build_runner: ^1.7.4

flutter:
  uses-material-design: true
  fonts:
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/Pokemon-Hollow.ttf
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/Pokemon-Solid.ttf
